server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mybatis.model